import json
import uuid
import pytest

from app.domain.content_plan import ContentBeat
from app.domain.enums import BeatType, StoryboardSnapshotState, VisualType
from app.domain.shot import Shot, ShotRevision
from app.domain.storyboard import StoryboardSnapshot
from app.domain.storyboard_agent import (
    InsufficientEvidenceError,
    InvalidShotDurationError,
    InvalidShotOrderError,
    ShotLimitExceededError,
    StoryboardAgent,
    StoryboardExecutionResult,
    StoryboardOutputInvalidError,
    StoryboardOutputSchemaError,
    StoryboardPlanningInput,
    UnsupportedEvidenceReferenceError,
)


class InMemoryShotRepo:
    def __init__(self):
        self.shots: dict[str, Shot] = {}
        self.revisions: dict[str, ShotRevision] = {}

    def add_shot(self, shot: Shot) -> Shot:
        self.shots[shot.shot_id] = shot
        return shot

    def add_revision(self, revision: ShotRevision) -> ShotRevision:
        self.revisions[revision.shot_revision_id] = revision
        return revision


class InMemoryStoryboardRepo:
    def __init__(self):
        self.snapshots: dict[str, StoryboardSnapshot] = {}

    def add_snapshot(self, snapshot: StoryboardSnapshot) -> StoryboardSnapshot:
        self.snapshots[snapshot.storyboard_snapshot_id] = snapshot
        return snapshot


def _make_sample_shot_dict(
    planner_ref="s1",
    local_order=1,
    narration="This is the narration explaining the beat concept clearly.",
    target_duration=10.0,
    visual_goal="Establish visual context",
    visual_type=VisualType.STOCK_VIDEO.value,
    scene_description="Wide shot of a modern laboratory",
    generation_prompt="Cinematic shot of modern research facility with glowing screens",
    camera_movement="Slow pan right",
    evidence_refs=None,
):
    return {
        "planner_ref": planner_ref,
        "local_order": local_order,
        "narration": narration,
        "target_duration": target_duration,
        "visual_goal": visual_goal,
        "visual_type": visual_type,
        "scene_description": scene_description,
        "generation_prompt": generation_prompt,
        "camera_movement": camera_movement,
        "evidence_refs": evidence_refs or [],
    }


def _make_sample_storyboard_json(beat_ref="beat-instance-1", shots=None):
    if shots is None:
        shots = [_make_sample_shot_dict()]
    return json.dumps({
        "beat_ref": beat_ref,
        "shots": shots,
    })


def _create_standard_beat(beat_type=BeatType.HOOK, target_duration=15.0):
    return ContentBeat(
        beat_id="beat-instance-1",
        beat_lineage_id="beat-lineage-1",
        beat_type=beat_type,
        order=1,
        intent="Hook the audience with an engaging hook",
        target_duration=target_duration,
        importance=0.9,
        evidence_refs=("ev1",) if beat_type == BeatType.KNOWLEDGE else (),
    )


# 1. One ContentBeat can produce one or more Shots
def test_one_content_beat_can_produce_multiple_shots():
    beat = _create_standard_beat(beat_type=BeatType.HOOK, target_duration=15.0)
    input_data = StoryboardPlanningInput(
        content_plan_revision_id="plan-rev-1",
        beat=beat,
        video_title="Quantum Physics",
    )
    shots_data = [
        _make_sample_shot_dict(
            planner_ref="s1",
            local_order=1,
            target_duration=7.5,
        ),
        _make_sample_shot_dict(
            planner_ref="s2",
            local_order=2,
            target_duration=7.5,
            visual_type=VisualType.DIAGRAM.value,
        ),
    ]
    agent = StoryboardAgent(llm_caller=lambda p: _make_sample_storyboard_json(shots=shots_data))
    result = agent.generate_shots_for_beat(input_data)

    assert isinstance(result, StoryboardExecutionResult)
    assert len(result.shots) == 2
    assert len(result.shot_revisions) == 2


# 2. Every generated Shot receives a system-owned shot_id
def test_every_generated_shot_receives_system_owned_shot_id():
    beat = _create_standard_beat(target_duration=10.0)
    input_data = StoryboardPlanningInput(
        content_plan_revision_id="plan-rev-1",
        beat=beat,
    )
    agent = StoryboardAgent(
        llm_caller=lambda p: _make_sample_storyboard_json(
            shots=[_make_sample_shot_dict(planner_ref="s_custom_ref_1")]
        )
    )
    result = agent.generate_shots_for_beat(input_data)

    assert len(result.shots) == 1
    shot = result.shots[0]

    # Valid UUID generated by system
    uuid.UUID(shot.shot_id)
    # The temporary planner_ref was NOT used as shot_id
    assert shot.shot_id != "s_custom_ref_1"


# 3. Every initial ShotRevision receives a system-owned revision ID
def test_every_initial_shot_revision_receives_system_owned_revision_id():
    beat = _create_standard_beat(target_duration=10.0)
    input_data = StoryboardPlanningInput(
        content_plan_revision_id="plan-rev-1",
        beat=beat,
    )
    agent = StoryboardAgent(llm_caller=lambda p: _make_sample_storyboard_json())
    result = agent.generate_shots_for_beat(input_data)

    shot = result.shots[0]
    rev = result.shot_revisions[0]

    uuid.UUID(rev.shot_revision_id)
    assert rev.shot_id == shot.shot_id
    assert rev.revision_number == 1
    assert rev.narration == "This is the narration explaining the beat concept clearly."
    assert rev.visual_type == VisualType.STOCK_VIDEO


# 4. LLM output cannot override shot_id, shot_revision_id, beat_lineage_id
def test_llm_cannot_override_identities():
    malicious_json = json.dumps({
        "beat_ref": "b1",
        "shots": [
            {
                "planner_ref": "s1",
                "local_order": 1,
                "narration": "Narration",
                "target_duration": 10.0,
                "visual_goal": "Goal",
                "visual_type": "STOCK_VIDEO",
                "scene_description": "Scene",
                "generation_prompt": "Prompt",
                "camera_movement": "Pan",
                "evidence_refs": [],
                "shot_id": "malicious-shot-id-999",  # Forbidden!
            }
        ],
    })
    beat = _create_standard_beat(target_duration=10.0)
    agent = StoryboardAgent(llm_caller=lambda p: malicious_json)

    with pytest.raises(StoryboardOutputSchemaError):
        agent.generate_shots_for_beat(
            StoryboardPlanningInput(content_plan_revision_id="p1", beat=beat)
        )


# 5. Generated Shots preserve Beat lineage and exact originating Beat instance
def test_generated_shots_preserve_lineage_and_originating_beat_instance():
    beat = ContentBeat(
        beat_id="specific-beat-instance-42",
        beat_lineage_id="specific-beat-lineage-100",
        beat_type=BeatType.HOOK,
        order=2,
        intent="Hook",
        target_duration=10.0,
        importance=0.8,
    )
    input_data = StoryboardPlanningInput(
        content_plan_revision_id="p1",
        beat=beat,
    )
    agent = StoryboardAgent(llm_caller=lambda p: _make_sample_storyboard_json())
    result = agent.generate_shots_for_beat(input_data)

    shot = result.shots[0]
    rev = result.shot_revisions[0]

    assert shot.beat_lineage_id == "specific-beat-lineage-100"
    assert rev.beat_lineage_id == "specific-beat-lineage-100"
    assert rev.created_from_beat_instance_id == "specific-beat-instance-42"


# 6. Shot local_order is deterministic and valid
def test_shot_local_order_is_deterministic_and_valid():
    beat = _create_standard_beat(target_duration=20.0)
    shots_data = [
        _make_sample_shot_dict(planner_ref="s1", local_order=1, target_duration=10.0),
        _make_sample_shot_dict(planner_ref="s2", local_order=2, target_duration=10.0),
    ]
    agent = StoryboardAgent(llm_caller=lambda p: _make_sample_storyboard_json(shots=shots_data))
    result = agent.generate_shots_for_beat(
        StoryboardPlanningInput(content_plan_revision_id="p1", beat=beat)
    )

    assert result.shots[0].local_order == 1
    assert result.shots[1].local_order == 2


# 7. Duplicate/invalid local_order is rejected
@pytest.mark.parametrize(
    "invalid_orders",
    [
        [2, 3],  # Doesn't start at 1
        [1, 1],  # Duplicate
        [1, 3],  # Gap in sequence
    ],
)
def test_duplicate_or_invalid_local_order_is_rejected(invalid_orders):
    beat = _create_standard_beat(target_duration=20.0)
    shots_data = [
        _make_sample_shot_dict(planner_ref="s1", local_order=invalid_orders[0], target_duration=10.0),
        _make_sample_shot_dict(planner_ref="s2", local_order=invalid_orders[1], target_duration=10.0),
    ]
    agent = StoryboardAgent(llm_caller=lambda p: _make_sample_storyboard_json(shots=shots_data))

    with pytest.raises(InvalidShotOrderError):
        agent.generate_shots_for_beat(
            StoryboardPlanningInput(content_plan_revision_id="p1", beat=beat)
        )


# 8. Unsupported VisualType is rejected
def test_unsupported_visual_type_is_rejected():
    beat = _create_standard_beat(target_duration=10.0)
    shots_data = [
        _make_sample_shot_dict(visual_type="3D_HOLOGRAM_VFX")  # Non-existent visual type
    ]
    agent = StoryboardAgent(llm_caller=lambda p: _make_sample_storyboard_json(shots=shots_data))

    with pytest.raises(StoryboardOutputSchemaError):
        agent.generate_shots_for_beat(
            StoryboardPlanningInput(content_plan_revision_id="p1", beat=beat)
        )


# 9. Factual narration with unsupported evidence is rejected in source-grounded mode
def test_factual_narration_with_unsupported_evidence_rejected():
    knowledge_beat = ContentBeat(
        beat_id="k-beat-1",
        beat_lineage_id="k-lineage-1",
        beat_type=BeatType.KNOWLEDGE,
        order=1,
        intent="Explain empirical findings",
        target_duration=10.0,
        importance=1.0,
        evidence_refs=("ev_grounded_1",),
    )

    # Case A: KNOWLEDGE beat produces shots with no evidence citations
    shots_no_ev = [_make_sample_shot_dict(evidence_refs=[])]
    agent = StoryboardAgent(llm_caller=lambda p: _make_sample_storyboard_json(shots=shots_no_ev))
    with pytest.raises(InsufficientEvidenceError) as exc_info:
        agent.generate_shots_for_beat(
            StoryboardPlanningInput(
                content_plan_revision_id="p1",
                beat=knowledge_beat,
                source_grounded=True,
            )
        )
    assert "requires verified evidence citations" in str(exc_info.value)

    # Case B: Shot cites an evidence ID not present in available_evidence_ids
    shots_unallowed_ev = [_make_sample_shot_dict(evidence_refs=["hallucinated_paper_99"])]
    agent2 = StoryboardAgent(
        llm_caller=lambda p: _make_sample_storyboard_json(shots=shots_unallowed_ev)
    )
    with pytest.raises(UnsupportedEvidenceReferenceError) as exc_info2:
        agent2.generate_shots_for_beat(
            StoryboardPlanningInput(
                content_plan_revision_id="p1",
                beat=knowledge_beat,
                available_evidence_ids=("ev_grounded_1",),
                source_grounded=True,
            )
        )
    assert "hallucinated_paper_99" in str(exc_info2.value)


# 10. Planned Shot duration must stay within the Beat-level tolerance
def test_planned_shot_duration_must_stay_within_tolerance():
    beat = _create_standard_beat(target_duration=20.0)

    # 20.0s target, 0.20 tolerance -> max deviation 4.0s (16.0s - 24.0s allowed)
    # Proposing 5.0s total -> invalid
    shots_too_short = [_make_sample_shot_dict(target_duration=5.0)]
    agent_short = StoryboardAgent(
        llm_caller=lambda p: _make_sample_storyboard_json(shots=shots_too_short)
    )
    with pytest.raises(InvalidShotDurationError) as exc_info:
        agent_short.generate_shots_for_beat(
            StoryboardPlanningInput(content_plan_revision_id="p1", beat=beat)
        )
    assert "deviates from beat target" in str(exc_info.value)

    # Proposing 35.0s total -> invalid
    shots_too_long = [_make_sample_shot_dict(target_duration=35.0)]
    agent_long = StoryboardAgent(
        llm_caller=lambda p: _make_sample_storyboard_json(shots=shots_too_long)
    )
    with pytest.raises(InvalidShotDurationError):
        agent_long.generate_shots_for_beat(
            StoryboardPlanningInput(content_plan_revision_id="p1", beat=beat)
        )


# 11. Excessive Shot count is rejected
def test_excessive_shot_count_is_rejected():
    beat = _create_standard_beat(target_duration=35.0)
    # Default limit is 6 shots per beat, propose 7
    shots_7 = [
        _make_sample_shot_dict(planner_ref=f"s{i}", local_order=i, target_duration=5.0)
        for i in range(1, 8)
    ]
    agent = StoryboardAgent(
        llm_caller=lambda p: _make_sample_storyboard_json(shots=shots_7),
        max_shots_per_beat=6,
    )

    with pytest.raises(ShotLimitExceededError) as exc_info:
        agent.generate_shots_for_beat(
            StoryboardPlanningInput(content_plan_revision_id="p1", beat=beat)
        )
    assert "exceeds maximum allowed shots per beat (6)" in str(exc_info.value)


# 12. Storyboard retry is bounded
def test_storyboard_retry_is_bounded():
    beat = _create_standard_beat(target_duration=10.0)
    input_data = StoryboardPlanningInput(content_plan_revision_id="p1", beat=beat)

    # Scenario A: Initial call returns broken JSON, second attempt repairs and succeeds
    call_count = 0
    prompts = []

    def healing_llm(prompt: str) -> str:
        nonlocal call_count
        call_count += 1
        prompts.append(prompt)
        if call_count == 1:
            return "broken json"
        return _make_sample_storyboard_json()

    agent_heal = StoryboardAgent(llm_caller=healing_llm, max_retries=2)
    result = agent_heal.generate_shots_for_beat(input_data)
    assert len(result.shots) == 1
    assert call_count == 2
    assert "[Correction Notice]" in prompts[1]

    # Scenario B: Always fails, terminates boundedly after max_retries + 1
    fail_count = 0

    def always_fail_llm(prompt: str) -> str:
        nonlocal fail_count
        fail_count += 1
        return "unfixable json"

    agent_fail = StoryboardAgent(llm_caller=always_fail_llm, max_retries=2)
    with pytest.raises(StoryboardOutputSchemaError):
        agent_fail.generate_shots_for_beat(input_data)
    assert fail_count == 3


# 13. No Asset generation provider is called
def test_no_asset_generation_provider_is_called(monkeypatch):
    # Verify StoryboardAgent does not invoke any provider or media generation
    beat = _create_standard_beat(target_duration=10.0)
    shots_data = [
        _make_sample_shot_dict(
            visual_type=VisualType.AI_VIDEO.value,
            generation_prompt="Ultra-detailed DNA helix rotating in 3D",
        )
    ]
    agent = StoryboardAgent(llm_caller=lambda p: _make_sample_storyboard_json(shots=shots_data))
    result = agent.generate_shots_for_beat(
        StoryboardPlanningInput(content_plan_revision_id="p1", beat=beat)
    )

    # Only pure domain planning objects were created
    rev = result.shot_revisions[0]
    assert rev.visual_type == VisualType.AI_VIDEO
    assert rev.generation_prompt == "Ultra-detailed DNA helix rotating in 3D"
    # No media file paths, no execution status, no provider IDs on the revision
    assert not hasattr(rev, "provider")
    assert not hasattr(rev, "video_url")


# 14. If a StoryboardSnapshot is created, it contains exact ShotRevision IDs
def test_storyboard_snapshot_contains_exact_shot_revision_ids():
    beat = _create_standard_beat(target_duration=10.0)
    agent = StoryboardAgent(llm_caller=lambda p: _make_sample_storyboard_json())
    result = agent.generate_shots_for_beat(
        StoryboardPlanningInput(content_plan_revision_id="plan-rev-10", beat=beat)
    )

    snapshot_repo = InMemoryStoryboardRepo()
    snapshot = agent.create_draft_snapshot(
        content_plan_revision_id="plan-rev-10",
        shot_revisions=result.shot_revisions,
        storyboard_repository=snapshot_repo,
    )

    assert isinstance(snapshot, StoryboardSnapshot)
    assert snapshot.snapshot_state == StoryboardSnapshotState.DRAFT
    assert snapshot.content_plan_revision_id == "plan-rev-10"
    assert snapshot.shot_revision_ids == (result.shot_revisions[0].shot_revision_id,)
    # Persisted into repo
    assert snapshot.storyboard_snapshot_id in snapshot_repo.snapshots


# Extra: Persistence integration with ShotRepository
def test_shots_persist_through_repository():
    beat = _create_standard_beat(target_duration=10.0)
    shot_repo = InMemoryShotRepo()

    agent = StoryboardAgent(
        shot_repository=shot_repo,
        llm_caller=lambda p: _make_sample_storyboard_json(),
    )
    result = agent.generate_shots_for_beat(
        StoryboardPlanningInput(content_plan_revision_id="plan-rev-10", beat=beat)
    )

    assert len(shot_repo.shots) == 1
    assert len(shot_repo.revisions) == 1
    assert result.shots[0].shot_id in shot_repo.shots
    assert result.shot_revisions[0].shot_revision_id in shot_repo.revisions
